"""url and github sources

Revision ID: 326c4a6ded9b
Revises: 8ba88c2e0b43
Create Date: 2026-07-28 13:50:10.919572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326c4a6ded9b'
down_revision: Union[str, Sequence[str], None] = '8ba88c2e0b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate does not see enum labels. ADD VALUE is fine inside a
    # transaction on this Postgres as long as the label is not used in it.
    for label in ('DOCX', 'PPTX', 'XLSX', 'URL', 'GITHUB'):
        op.execute(f"ALTER TYPE sourcetype ADD VALUE IF NOT EXISTS '{label}'")
    op.add_column('sources', sa.Column('origin', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'origin')
    # Postgres cannot drop enum labels; the extra ones linger harmlessly.
    # ### end Alembic commands ###
