"""source progress

Revision ID: 8ba88c2e0b43
Revises: 2a42b144c557
Create Date: 2026-07-27 16:19:10.818943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba88c2e0b43'
down_revision: Union[str, Sequence[str], None] = '2a42b144c557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows need a value before the constraint can hold.
    op.add_column(
        'sources',
        sa.Column('progress', sa.Float(), nullable=False, server_default='0'),
    )
    op.add_column('sources', sa.Column('progress_detail', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'progress_detail')
    op.drop_column('sources', 'progress')
    # ### end Alembic commands ###
