"""parent child chunks

Revision ID: a3175d0209aa
Revises: aa8476f11191
Create Date: 2026-07-26 23:18:27.956964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3175d0209aa'
down_revision: Union[str, Sequence[str], None] = 'aa8476f11191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_parents',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('heading_path', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_parents_workspace_id'), 'chunk_parents', ['workspace_id'], unique=False)
    # Chunks are derived data and every source must be re-ingested for the new
    # parent/child split anyway, so clear them rather than back-fill.
    op.execute('DELETE FROM chunks')
    op.execute("UPDATE sources SET status = 'PENDING'")
    op.add_column('chunks', sa.Column('parent_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'chunks', 'chunk_parents', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM chunks')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_column('chunks', 'parent_id')
    op.drop_index(op.f('ix_chunk_parents_workspace_id'), table_name='chunk_parents')
    op.drop_table('chunk_parents')
    # ### end Alembic commands ###
