"""chunk parent images

Revision ID: d0f74d9a34e8
Revises: a3175d0209aa
Create Date: 2026-07-27 09:54:33.975151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0f74d9a34e8'
down_revision: Union[str, Sequence[str], None] = 'a3175d0209aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk_parents', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk_parents', 'images')
    # ### end Alembic commands ###
